RIGHT_ARROW_OUTLINE = '|\\ |\n|/ |'
LEFT_ARROW_OUTLINE = '| /|\n| \\|'
PLAY_OUTLINE = '|\\\n|/'
PAUSE_OUTLINE = '|| ||\n|| ||'
HEART_OUTLINE = ' _  _ \n/ \\/ \\\n\\    /\n \\  /\n  \\/'
HEART_SOLID = ' _  _ \n/&\\/&\\\n\\%##P/\n \\TT/\n  \\/'
# HEART_OUTLINE = ' _   _ \n/ \\-/ \\\n\\     /\n \\_ _/\n   V'
# HEART_OUTLINE = ' _   _ \n/ \\-/ \\\n\\     /\n \\   /\n  \\_/\n'
